### ISSUE TITLE
Make a release which references tagged system-modeller release

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller-deployment#16]
Currently we just have the main branch which pulls in the `system-modeller:dev-latest` docker image. We should have a "3.5.0" release which references system-modeller v3.5.0.

It might make sense to change the main branch to refer to system-modeller v3.5.0 and release off there and then make a dev branch which references system-modeller dev-latest (as the main one does now).

**Comment by kenmeacham** [comment]
> Currently we just have the main branch which pulls in the `system-modeller:dev-latest` docker image. We should have a "3.5.0" release which references system-modeller v3.5.0.
> 
> It might make sense to change the main branch to refer to system-modeller v3.5.0 and release off there and then make a dev branch which references system-modeller dev-latest (as the main one does now).

I made some progress on this. In the main branch I've set in .env:
`
SPYDERISK_VERSION=v3.5.0-latest
`

N.B. This still has the `-latest` tag ending because the docker image was created/named prior to creating the SSM action for publishing from a tag, with a tag such as `v3.5.0`; this will be available next time we release SSM.

One issue that we have is that we don't yet have versioned releases of ssm-adaptor. I presume that we will need this soon, so that we can ensure that we can release system-modeller-deployment with both a known version of SSM and a compatible version of ssm-adaptor? For now, I have used a specific dated version of ssm-adaptor which is known to be compativle with SSM v3.5.0:

`
SPYDERISK_ADAPTOR_VERSION=dev-20240517T1119
`

I then created a dev branch off the main branch, and set the following in .env:
```
SPYDERISK_VERSION=dev-latest
SPYDERISK_ADAPTOR_VERSION=dev-latest
```

This will use the latest dev docker images of these components, although we should be aware that compatability is not guaranteed in this case.

If you are happy with the above, I can try and create a release `v3.5.0` of system-modeller-deployment off the main branch.

CC @panositi

**Comment by scp93ch** [comment]
Sounds good. Might as well just add the "v3.5.0" tag to the existing system modeller image though rather than making do with "v3.5.0-latest".

**Comment by kenmeacham** [comment]
> Sounds good. Might as well just add the "v3.5.0" tag to the existing system modeller image though rather than making do with "v3.5.0-latest".

Yes, that would be ideal, but I don't see an option to do that on docker hub. Maybe I don't have permission to do that. In which case, could you make the change?

**Comment by kenmeacham** [comment]
> > Sounds good. Might as well just add the "v3.5.0" tag to the existing system modeller image though rather than making do with "v3.5.0-latest".
> 
> Yes, that would be ideal, but I don't see an option to do that on docker hub. Maybe I don't have permission to do that. In which case, could you make the change?

I've re-tagged the system modeller image as v3.5.0 and pushed to docker hub. The .env file has been updated accordingly.

**Comment by kenmeacham** [comment]
I've now created release v3.5.0 of system-modeller-deployment, which also available for download as a zip or tar.gz
https://github.com/Spyderisk/system-modeller-deployment/releases/tag/v3.5.0

Closing issue #16
