### ISSUE TITLE
Readme should cover installation on Windows

### ISSUE THREAD

**Issue by mike1813** [Spyderisk/system-modeller-deployment#9]
The README does mention installation on a Windows system, but it doesn't provide clear instructions:

- what version(s) of Windows do you need
- what Windows options should be enabled (e.g., WSL)
- what other software should you install first (e.g., Docker Desktop)
- what steps should you follow to get system modeller deployed and working
- what do you need to know to use the deployed system-modeller instance (if anything)

The steps to follow should be quite simple, given that Docker Desktop does some of the network configuration (e.g., an alias for the Docker host, which acts as the gateway to the deployed service).

Other stuff you might need to know could include things like how to access the system-modeller log and raise an issue reporting any problems (should something go wrong)

**Comment by scp93ch** [comment]
We discussed this yesterday and @mike1813 made the point that we must make it as easy as possible to get the system-modeller working on a personal computer (rather than a server) for people who want to do domain modelling (not software development).

The README has been improved, but we might want to consider making entirely separate instructions for Windows users (for instance), and those deploying on a server.

**Comment by danshearer** [comment]
I haven't finished testing on Windows, but I have improved the README all the same, including removing reference to Mac (which haven't tested so it doesn't exist) and Windows Server. Windows Server is not only difficult to test even if we wanted to due to Microsoft licensing decisions as now noted in the README, but it is also a generally bad idea and not even Microsoft recommends running Linux services on the internet under WSL as far as I know. At this point it does probably make sense to support Windows workstations via Docker and that is what we are aiming for here.

There are some other issues that arise, such as shipping a keycloak configuration which fails open rather than closed, which matters when it accidentally gets exposed to the internet. There are some simple things we can do to require the users to actively choose to turn on the default insecure config rather than just giving it to them that way. We have to provide something that is as easy as possible to get running too of course.
